import 'package:flutter/material.dart';
import 'package:flutter_quill/flutter_quill.dart';

class QuillToolBar extends StatelessWidget {
  const QuillToolBar({
    super.key,
    required QuillController quillController,
  }) : _quillController = quillController;

  final QuillController _quillController;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        QuillSimpleToolbar(
          configurations: QuillSimpleToolbarConfigurations(
            controller: _quillController,
            showBoldButton: true,
            showItalicButton: true,
            showStrikeThrough: true,
            showClearFormat: true,
            showSubscript: true,
            showSuperscript: true,
            showFontFamily: true,
            showFontSize: true,
            showColorButton: true,
            showBackgroundColorButton: true,
            showUnderLineButton: true,
            multiRowsDisplay: true,

            showInlineCode: false,
            showLineHeightButton: false,
            showAlignmentButtons: false,
            showHeaderStyle: false,
            showListNumbers: false,
            showListBullets: false,
            showListCheck: false,
            showCodeBlock: false,
            showQuote: false,
            showIndent: false,
            showLink: false,
            showUndo: false,
            showRedo: false,
            showDirection: false,
            showSearchButton: false,
            showClipboardCut: false,
            showClipboardCopy: false,
            showClipboardPaste: false,
            showCenterAlignment: false,
            showDividers: false,
            showJustifyAlignment: false,
            showLeftAlignment: false,
            showRightAlignment: false,
            showSmallButton: false,
          ),
        ),
        QuillSimpleToolbar(
          configurations: QuillSimpleToolbarConfigurations(
              controller: _quillController,
              showHeaderStyle: true,
              showQuote: true,
              showCodeBlock: true,
              showListNumbers: true,
              showListBullets: true,
              showListCheck: true,
              showLineHeightButton: true,
              showIndent: true,
              multiRowsDisplay: true,

              showBoldButton: false,
              showItalicButton: false,
              showStrikeThrough: false,
              showInlineCode: false,
              showClearFormat: false,
              showSubscript: false,
              showSuperscript: false,
              showFontFamily: false,
              showFontSize: false,
              showColorButton: false,
              showBackgroundColorButton: false,
              showAlignmentButtons: false,
              showLink: false,
              showUndo: false,
              showRedo: false,
              showDirection: false,
              showSearchButton: false,
              showClipboardCut: false,
              showClipboardCopy: false,
              showClipboardPaste: false,
              showCenterAlignment: false,
              showJustifyAlignment: false,
              showDividers: false,
              showLeftAlignment: false,
              showRightAlignment: false,
              showSmallButton: false,
              showUnderLineButton: false),
        ),
        QuillSimpleToolbar(
          configurations: QuillSimpleToolbarConfigurations(
            controller: _quillController,
            showAlignmentButtons: true,
            showDirection: true,
            multiRowsDisplay: true,

            showUnderLineButton: false,
            showDividers: false,
            showBoldButton: false,
            showItalicButton: false,
            showStrikeThrough: false,
            showInlineCode: false,
            showClearFormat: false,
            showSubscript: false,
            showSuperscript: false,
            showFontFamily: false,
            showFontSize: false,
            showColorButton: false,
            showBackgroundColorButton: false,
            showHeaderStyle: false,
            showQuote: false,
            showCodeBlock: false,
            showListNumbers: false,
            showListBullets: false,
            showListCheck: false,
            showLineHeightButton: false,
            showIndent: false,
            showLink: false,
            showUndo: false,
            showRedo: false,
            showSearchButton: false,
            showClipboardCut: false,
            showClipboardCopy: false,
            showClipboardPaste: false,
          ),
        ),
        QuillSimpleToolbar(
          configurations: QuillSimpleToolbarConfigurations(
            controller: _quillController,
            showLink: true,
            showClipboardCut: true,
            showClipboardCopy: true,
            showClipboardPaste: true,
            showUndo: true,
            showRedo: true,
            showSearchButton: true,
            multiRowsDisplay: true,

            showDividers: false,
            showUnderLineButton: false,
            showBoldButton: false,
            showItalicButton: false,
            showStrikeThrough: false,
            showInlineCode: false,
            showClearFormat: false,
            showSubscript: false,
            showSuperscript: false,
            showFontFamily: false,
            showFontSize: false,
            showColorButton: false,
            showBackgroundColorButton: false,
            showHeaderStyle: false,
            showQuote: false,
            showCodeBlock: false,
            showListNumbers: false,
            showListBullets: false,
            showListCheck: false,
            showLineHeightButton: false,
            showIndent: false,
            showAlignmentButtons: false,
            showDirection: false,
          ),
        ),
      ],
    );
  }
}
